In [15]:
%load_ext autoreload
%autoreload 2
%aimport -sympy

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [26]:
from planttraits.datasets.plant_traits_dataset import PlantTraitsDataset
from planttraits.models.example_model import PTNN, kwargs
from torch.utils.data import DataLoader
import pytorch_lightning as pl
import torch 

In [17]:
train_dataset = PlantTraitsDataset()
test_dataset = PlantTraitsDataset(preprocessors=train_dataset.return_preprocessors())

In [18]:
len(train_dataset)

55489

In [19]:
len(test_dataset)

6545

In [20]:
train_loader = DataLoader(train_dataset)
test_loader = DataLoader(test_dataset)

In [21]:
img, modisvod_row, soil_row, worldclimbio_row, std_row, mean_row = next(iter(train_loader))

In [22]:
std_row, mean_row

(tensor([[0., 0., 0., 0., 0., 0.]]),
 tensor([[ 0.4018, 11.7581,  0.1175,  1.2438,  1.8494, 50.2160]]))

In [23]:
model = PTNN(**kwargs)
trainer = pl.Trainer()

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs


In [24]:
preds = trainer.predict(model, test_loader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [27]:
preds = torch.concat(preds)

In [29]:
test_dataset.transform_predictions(preds)

tensor([[-0.2637, -0.2088,  0.8252,  0.2456,  0.2410,  0.2086],
        [-0.0426, -0.1486,  0.9101,  0.0452,  0.4008,  0.2653],
        [ 0.0164, -0.1243,  0.8046,  0.0996,  0.3274,  0.2304],
        ...,
        [-0.0981, -0.1709,  1.0170,  0.0776,  0.3972,  0.2430],
        [-0.0186, -0.1358,  0.9413,  0.1939,  0.2619,  0.2135],
        [-0.1785, -0.1609,  1.0010,  0.1188,  0.3301,  0.2591]])