In [1]:
%load_ext autoreload
%autoreload 2
%aimport -sympy

In [2]:
from planttraits.datasets.plant_traits_dataset import PlantTraitsDataset
from planttraits.models.example_model import PTNN, kwargs
from torch.utils.data import DataLoader
import pytorch_lightning as pl
import torch 

In [3]:
train_dataset = PlantTraitsDataset()
test_dataset = PlantTraitsDataset(preprocessors=train_dataset.return_preprocessors())

In [4]:
len(train_dataset.imgs_paths)

55489

In [5]:
len(train_dataset)

55327

In [6]:
len(test_dataset)

6545

In [7]:
train_loader = DataLoader(train_dataset)
test_loader = DataLoader(test_dataset)

In [8]:
img, modisvod_row, soil_row, worldclimbio_row, std_row, mean_row = next(iter(train_loader))

In [9]:
std_row, mean_row

(tensor([[0., 0., 0., 0., 0., 0.]]),
 tensor([[0.4018, 2.5462, 0.1111, 0.8082, 1.0471, 3.9361]]))

In [10]:
model = PTNN(**kwargs)
trainer = pl.Trainer()

Using default `ModelCheckpoint`. Consider installing `litmodels` package to enable `LitModelCheckpoint` for automatic upload to the Lightning model registry.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs


In [11]:
preds = trainer.predict(model, test_loader)

You are using a CUDA device ('NVIDIA GeForce RTX 4050 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [12]:
preds = torch.concat(preds)

In [13]:
test_dataset.transform_predictions(preds)

tensor([[-0.6513, -0.1920, -0.1454,  0.4568, -0.4089, -0.5358],
        [-0.4101, -0.3816, -0.2712,  0.5583, -0.4559, -0.4361],
        [-0.3087, -0.3777, -0.3510,  0.5858, -0.4262, -0.4403],
        ...,
        [-0.4560, -0.3569, -0.2663,  0.4780, -0.4594, -0.4601],
        [-0.3720, -0.3665, -0.3254,  0.5724, -0.4562, -0.4645],
        [-0.5281, -0.3564, -0.2614,  0.4585, -0.4490, -0.4578]])