In [13]:
%load_ext autoreload
%autoreload 2
%aimport -sympy

In [1]:
from planttraits.datasets.plant_traits_dataset import PlantTraitsDataset
from planttraits.models.example_model import PTNN, kwargs
from torch.utils.data import DataLoader
import pytorch_lightning as pl
import torch 

In [2]:
train_dataset = PlantTraitsDataset()
test_dataset = PlantTraitsDataset(preprocessors=train_dataset.return_preprocessors())

In [3]:
len(train_dataset.imgs_paths)

55489

In [4]:
len(train_dataset)

55489

In [5]:
len(test_dataset)

6545

In [6]:
train_loader = DataLoader(train_dataset)
test_loader = DataLoader(test_dataset)

In [7]:
img, modisvod_row, soil_row, worldclimbio_row, std_row, mean_row = next(iter(train_loader))

In [8]:
std_row, mean_row

(tensor([[0., 0., 0., 0., 0., 0.]]),
 tensor([[ 0.4018, 11.7581,  0.1175,  1.2438,  1.8494, 50.2160]]))

In [9]:
model = PTNN(**kwargs)
trainer = pl.Trainer()

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs


In [10]:
preds = trainer.predict(model, test_loader)

You are using a CUDA device ('NVIDIA GeForce RTX 4050 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [11]:
preds = torch.concat(preds)

In [12]:
test_dataset.transform_predictions(preds)

tensor([[-0.2686, -0.3257, -0.0650, -0.2402,  0.6723, -0.2981],
        [-0.2154, -0.3618,  0.0909, -0.2048,  0.4636, -0.2328],
        [-0.2504, -0.2247,  0.1227, -0.2817,  0.5432, -0.2816],
        ...,
        [-0.2310, -0.4614,  0.0559, -0.1025,  0.4592, -0.1981],
        [-0.0902, -0.2266,  0.0933, -0.2903,  0.5586, -0.2951],
        [-0.2648, -0.4479,  0.0436, -0.1592,  0.6215, -0.2389]])